BINARIES = race_condition race_condition_mutex race_condition_spinlock \
	race_condition_atomic_gcc race_condition_atomic_assembly
CFLAGS = -g -Wall -Wextra -Werror -I..
LDLIBS = -lpthread
include ../../../../../common/makefile/multiple.mk
