BINARIES = sum_array_threads sum_array_processes
include ../../../../../../common/makefile/multiple.mk

sum_array_threads: sum_array_threads.o generate_random_array.o

sum_array_processes: sum_array_processes.o generate_random_array.o
