name: Checkpatch Review

on: [pull_request]

jobs:
  review:
    name: Checkpatch Review
    runs-on: ubuntu-latest
    steps:
    - name: 'Calculate PR commits + 1'
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV

    - name: Checkout PR HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}

    - name: Info
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Workspace: $GITHUB_WORKSPACE"
        pwd
        ls -la `pwd`
        ls -la `pwd`/.github
        git log --oneline --graph


    - name: Copy checkpatch script
      run: cp ${{github.workspace}}/.github/checkpatch.conf ${{github.workspace}}/.checkpatch.conf


    - name: Run checkpatch review
      uses: webispy/checkpatch-action@v9
