name: Labeler Actions Workflow

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: open-education-hub/actions/cron-labeler@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
