BINARIES = pipe fifo unix_stream_socket_server unix_stream_socket_client unix_datagram_socket_server unix_datagram_socket_client network_stream_socket_server network_stream_socket_client network_datagram_socket_server network_datagram_socket_client
include ../../../../../common/makefile/multiple.mk
